name: Release Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Get tag directly from the push event
      - name: Get tag
        id: tag
        run: echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Build assets
        run: |
          VERSION=${{ steps.tag.outputs.version }}

          wget https://game-icons.net/archives/svg/zip/ffffff/000000/game-icons.net.svg.zip
          7z e game-icons.net.svg.zip -aou -oblackbackground *.svg -r && rm game-icons.net.svg.zip
          sed -i 's/viewBox="0 0 512 512"/viewBox="0 0 512 512" width="512" height="512"/g' blackbackground/*.svg

          wget https://game-icons.net/archives/svg/zip/000000/ffffff/game-icons.net.svg.zip
          7z e game-icons.net.svg.zip -aou -owhitebackground *.svg -r && rm game-icons.net.svg.zip
          sed -i 's/viewBox="0 0 512 512"/viewBox="0 0 512 512" width="512" height="512"/g' whitebackground/*.svg

          wget https://game-icons.net/archives/svg/zip/000000/transparent/game-icons.net.svg.zip
          7z e game-icons.net.svg.zip -aou -oblacktransparent *.svg -r && rm game-icons.net.svg.zip
          sed -i 's/viewBox="0 0 512 512"/viewBox="0 0 512 512" width="512" height="512"/g' blacktransparent/*.svg

          wget https://game-icons.net/archives/svg/zip/ffffff/transparent/game-icons.net.svg.zip
          7z e game-icons.net.svg.zip -aou -owhitetransparent *.svg -r && rm game-icons.net.svg.zip
          sed -i 's/viewBox="0 0 512 512"/viewBox="0 0 512 512" width="512" height="512"/g' whitetransparent/*.svg

          # Update module.json
          sed -i "s/\"version\":.*/\"version\": \"${VERSION}\",/" module.json
          sed -i "s|\"download\":.*|\"download\": \"https://github.com/datdamnzotz/icons/releases/download/${VERSION}/${VERSION}.zip\"|" module.json

          # Create zip
          7z a -tzip ${VERSION}.zip black* white* README* license.txt module.json -mx0 -xr!.git -xr!.github

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.version }}
          name: ${{ steps.tag.outputs.version }}
          files: ${{ steps.tag.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit updated module.json
        uses: EndBug/add-and-commit@v9
        with:
          ref: master
          message: "Update module.json for ${{ steps.tag.outputs.version }}"
          add: module.json